{{- if and (.Values.appFoo.enabled) (.Values.appFoo.hpa) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appFoo.label }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appFoo.label }}
  minReplicas: {{ .Values.appFoo.hpa.minReplicaCount }}
  maxReplicas: {{ .Values.appFoo.hpa.maxReplicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.appFoo.hpa.averageUtilization }}
{{- end }}
