{{- if and (.Values.appBar.enabled) (.Values.appBar.scaledObject) }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appBar.label }}-hpa
spec:
  maxReplicas: 4
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: app-bar
  targetCPUUtilizationPercentage: 40
{{- end }}
