apiVersion: v2
name: java-monorepo
description: Chart for the java monorepo app
version: appVersion
#appVersion: appVersion
#dependencies:
#  - name: "mongodb"
#    version: "4.4.13"
#    repository: "https://charts.bitnami.com/bitnami"
#    condition: mongodb.enabled
#  - name: "zookeeper"
#    version: "3.8.0"
#    repository: "https://charts.bitnami.com/bitnami"
#    condition: zookeeper.enabled
#  - name: "kafka"
#    version: "3.1.0"
#    repository: "https://charts.bitnami.com/bitnami"
#    condition: kafka.enabled
#  - name: "redis"
#    version: "16.3.0"
#    repository: "https://charts.bitnami.com/bitnami"
#    condition: redis.enabled