{{- if .Values.appFoo.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appFoo.label }}-secret
  labels:
    {{- include "myapp-monorepo.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.appFoo.env.secret }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}