{{- if .Values.appFoo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: app-foo
  labels:
    {{- include "myapp-monorepo.labels" . | nindent 4 }}
    app: {{ include "myapp-monorepo.fullname" . }}
spec:
  type: {{ .Values.appFoo.service.type }}
  ports:
    - port: {{ .Values.appFoo.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: app-foo
{{- end }}