on:
  workflow_call:
    inputs:
      appname:
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Depdendencies
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Setup JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build
        run: mvn clean package --projects :${{ inputs.appname }} --also-make --threads=2 --batch-mode

      - name: Docker - Login to Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker - Build image and push to Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: ./apps/${{ inputs.appname }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/java-monorepo.apps.${{ inputs.appname }}:latest
            ${{ secrets.DOCKER_USERNAME }}/java-monorepo.apps.${{ inputs.appname }}:${{ github.run_number }}