name: Build, Image and Deploy

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feat/*'
    paths:
      - 'apps/**'
      - 'libs/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'feat/*'
    paths:
      - 'apps/**'
      - 'libs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  app-bar:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      app-name: bar
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}

  app-baz:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      app-name: baz
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}

  app-foo:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      app-name: foo
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    needs:
      - 'app-bar'
      - 'app-baz'
      - 'app-foo'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy....
        run: echo Deploy app