on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
    secrets:
      docker-username:
        required: true
      docker-token:
        required: true

jobs:
  build-test-image:
    name: build-test-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Depdendencies
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Setup JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build, Test and Package
        run: mvn clean package --projects :${{ inputs.app-name }} --also-make --threads=2 --batch-mode

      - name: Docker - Login to Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-token }}

      - name: Docker - Build image and push to Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: ./apps/${{ inputs.app-name }}
          push: true
          tags: |
            ${{ secrets.docker-username }}/java-monorepo.apps.${{ inputs.app-name }}:latest
            ${{ secrets.docker-token }}/java-monorepo.apps.${{ inputs.app-name }}:${{ github.run_number }}