name: Chart deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Prep helm chart
        run: |
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> test.yaml &&
          cat test.yaml
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade java-monorepo ./k8s/ --install --wait --atomic --namespace=${{ secrets.KUBENAMESPACE }} --set=app.name=java-monorepo --values=./k8s/values.yaml
          kubeconfig: '${{ secrets.KUBECONFIG }}'
