name: Is Alive

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - name: Server Test
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" https://${{ secrets.KUBENAMESPACE }}.cloud.okteto.net/app-bar/actuator/health) >> $GITHUB_ENV
          echo "$STATUS_CODE"
          if [[ $STATUS_CODE == "200" ]] ; then echo "Server is alive!" ; else echo "Server is off" ; exit 1; fi

