name: Is Alive

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:

  is-alive-app-bar:
    uses: ./.github/workflows/is-alive-reusable.yaml
    with:
      app-name: bar
    secrets:
      namespace: ${{ secrets.KUBENAMESPACE }}

  is-alive-app-baz:
    uses: ./.github/workflows/is-alive-reusable.yaml
    with:
      app-name: baz
    secrets:
      namespace: ${{ secrets.KUBENAMESPACE }}

  is-alive-app-foo:
    uses: ./.github/workflows/is-alive-reusable.yaml
    with:
      app-name: foo
    secrets:
      namespace: ${{ secrets.KUBENAMESPACE }}