name: JMeter Test

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  tests-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: ./apps/bar/src/test/resources/test-plan-track.jmx
          outputReportsFolder: ./reports/
          args: "--loglevel INFO"
          retention-days: 7

      - uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: ./reports/
