name: Container Registry Cleaner

on:
  schedule:
  - cron: '* 5 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Container Registry Cleaner
