name: Cron job

on:
  schedule:
  - cron: '5 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
